# Generated by Django 4.0.1 on 2022-01-26 10:12

import datetime
from django.db import migrations, models
import imageuploader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('form_id', models.CharField(default=1, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('time_now', models.DateField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to=imageuploader.models.content_file_name)),
                ('type_data', models.CharField(blank=True, default='Massavi', max_length=50, null=True)),
                ('district', models.CharField(blank=True, choices=[('Abbotabad', 'Abbotabad'), ('Bahawalpur', 'Bahawalpur'), ('Charsaddah', 'Charsaddah'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Faisalabad', 'Faisalabad'), ('Gawadar', 'Gawadar'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Karachi', 'Karachi'), ('Lahore', 'Lahore'), ('Multan', 'Multan'), ('None', 'None')], max_length=50, null=True)),
                ('tehsil', models.CharField(blank=True, choices=[('Abbotabad', 'Abbotabad'), ('Bahawalpur', 'Bahawalpur'), ('Charsaddah', 'Charsaddah'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Faisalabad', 'Faisalabad'), ('Gawadar', 'Gawadar'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Karachi', 'Karachi'), ('Lahore', 'Lahore'), ('Multan', 'Multan'), ('None', 'None')], max_length=50, null=True)),
                ('patwar_circle', models.CharField(blank=True, choices=[('Abbotabad', 'Abbotabad'), ('Bahawalpur', 'Bahawalpur'), ('Charsaddah', 'Charsaddah'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Faisalabad', 'Faisalabad'), ('Gawadar', 'Gawadar'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Karachi', 'Karachi'), ('Lahore', 'Lahore'), ('Multan', 'Multan'), ('None', 'None')], max_length=50, null=True)),
                ('mauza', models.CharField(blank=True, choices=[('Abbotabad', 'Abbotabad'), ('Bahawalpur', 'Bahawalpur'), ('Charsaddah', 'Charsaddah'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Faisalabad', 'Faisalabad'), ('Gawadar', 'Gawadar'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Karachi', 'Karachi'), ('Lahore', 'Lahore'), ('Multan', 'Multan'), ('None', 'None')], max_length=50, null=True)),
                ('massavi_no', models.CharField(blank=True, choices=[('Alif-1', 'Alif-1'), ('Bay-1', 'Bay-1'), ('Jeem-1', 'Jeem-1'), ('Daal-1', 'Daal-1'), ('Hay-1', 'Hay-1'), ('Wao-1', 'Wao-1'), ('None', 'None')], max_length=50, null=True)),
            ],
        ),
    ]
