# Generated by Django 4.0 on 2022-01-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0003_remove_uploadimage_caption_uploadimage_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='desc',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image_id',
            field=models.CharField(default=1, max_length=20, unique=True),
        ),
    ]
