# Generated by Django 4.0 on 2022-01-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0004_uploadimage_desc_alter_uploadimage_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='desc',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
