# Generated by Django 4.0 on 2022-01-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0006_remove_uploadimage_id_alter_uploadimage_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image_id',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
