# Generated by Django 4.0 on 2022-01-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0007_alter_uploadimage_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='district',
            field=models.CharField(default='district', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='massavi_no',
            field=models.CharField(default='massavi_no', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='mauza',
            field=models.CharField(default='mauza', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='patwar_circle',
            field=models.CharField(default='patwar_circle', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='tehsil',
            field=models.CharField(default='tehsil', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='type_data',
            field=models.CharField(default='data_type', max_length=50),
        ),
    ]
