# Generated by Django 4.0 on 2022-01-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0008_uploadimage_district_uploadimage_massavi_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='desc',
        ),
    ]
