# Generated by Django 4.0 on 2022-01-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0009_remove_uploadimage_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='district',
            field=models.CharField(blank=True, default='district', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='massavi_no',
            field=models.CharField(blank=True, default='massavi_no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='mauza',
            field=models.CharField(blank=True, default='mauza', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='patwar_circle',
            field=models.CharField(blank=True, default='patwar_circle', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='tehsil',
            field=models.CharField(blank=True, default='tehsil', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='type_data',
            field=models.CharField(blank=True, default='data_type', max_length=50, null=True),
        ),
    ]
