# Generated by Django 4.0 on 2022-01-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0010_alter_uploadimage_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='massavi_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='mauza',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='patwar_circle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='tehsil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='type_data',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
