# Generated by Django 4.0 on 2022-01-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0012_rename_image_id_uploadimage_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='cities',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
