# Generated by Django 4.0 on 2022-01-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0013_uploadimage_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='cities_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cities', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='cities',
        ),
    ]
