# Generated by Django 4.0 on 2022-01-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0014_cities_list_remove_uploadimage_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='district',
            field=models.CharField(blank=True, choices=[('1', 'Abbotabad'), ('2', 'Bahawalpur'), ('3', 'Charsaddah'), ('4', 'Dera Ghazi Khan'), ('5', 'Faisalabad'), ('6', 'Gawadar'), ('7', 'Islamabad'), ('8', 'Rawalpindi'), ('9', 'Karachi'), ('10', 'Faislabad'), ('11', 'Lahore'), ('12', 'Multan')], max_length=50, null=True),
        ),
    ]
