# Generated by Django 4.0 on 2022-01-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0015_alter_uploadimage_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='mauza',
            field=models.CharField(blank=True, choices=[('1', 'Abbotabad'), ('2', 'Bahawalpur'), ('3', 'Charsaddah'), ('4', 'Dera Ghazi Khan'), ('5', 'Faisalabad'), ('6', 'Gawadar'), ('7', 'Islamabad'), ('8', 'Rawalpindi'), ('9', 'Karachi'), ('10', 'Faislabad'), ('11', 'Lahore'), ('12', 'Multan')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='patwar_circle',
            field=models.CharField(blank=True, choices=[('1', 'Abbotabad'), ('2', 'Bahawalpur'), ('3', 'Charsaddah'), ('4', 'Dera Ghazi Khan'), ('5', 'Faisalabad'), ('6', 'Gawadar'), ('7', 'Islamabad'), ('8', 'Rawalpindi'), ('9', 'Karachi'), ('10', 'Faislabad'), ('11', 'Lahore'), ('12', 'Multan')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='tehsil',
            field=models.CharField(blank=True, choices=[('1', 'Abbotabad'), ('2', 'Bahawalpur'), ('3', 'Charsaddah'), ('4', 'Dera Ghazi Khan'), ('5', 'Faisalabad'), ('6', 'Gawadar'), ('7', 'Islamabad'), ('8', 'Rawalpindi'), ('9', 'Karachi'), ('10', 'Faislabad'), ('11', 'Lahore'), ('12', 'Multan')], max_length=50, null=True),
        ),
    ]
