# Generated by Django 4.0 on 2022-01-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0016_alter_uploadimage_mauza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='district',
            field=models.CharField(blank=True, choices=[('Abbotabad', 'Abbotabad'), ('Bahawalpur', 'Bahawalpur'), ('Charsaddah', 'Charsaddah'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Faisalabad', 'Faisalabad'), ('Gawadar', 'Gawadar'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Karachi', 'Karachi'), ('Faislabad', 'Faislabad'), ('Lahore', 'Lahore'), ('Multan', 'Multan')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='mauza',
            field=models.CharField(blank=True, choices=[('Abbotabad', 'Abbotabad'), ('Bahawalpur', 'Bahawalpur'), ('Charsaddah', 'Charsaddah'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Faisalabad', 'Faisalabad'), ('Gawadar', 'Gawadar'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Karachi', 'Karachi'), ('Faislabad', 'Faislabad'), ('Lahore', 'Lahore'), ('Multan', 'Multan')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='patwar_circle',
            field=models.CharField(blank=True, choices=[('Abbotabad', 'Abbotabad'), ('Bahawalpur', 'Bahawalpur'), ('Charsaddah', 'Charsaddah'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Faisalabad', 'Faisalabad'), ('Gawadar', 'Gawadar'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Karachi', 'Karachi'), ('Faislabad', 'Faislabad'), ('Lahore', 'Lahore'), ('Multan', 'Multan')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='tehsil',
            field=models.CharField(blank=True, choices=[('Abbotabad', 'Abbotabad'), ('Bahawalpur', 'Bahawalpur'), ('Charsaddah', 'Charsaddah'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Faisalabad', 'Faisalabad'), ('Gawadar', 'Gawadar'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Karachi', 'Karachi'), ('Faislabad', 'Faislabad'), ('Lahore', 'Lahore'), ('Multan', 'Multan')], max_length=50, null=True),
        ),
    ]
