# Generated by Django 4.0 on 2022-01-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0017_alter_uploadimage_district_alter_uploadimage_mauza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geeks_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
