# Generated by Django 4.0 on 2022-01-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0018_geeks_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='massavi_no',
            field=models.CharField(blank=True, choices=[('Alif-1', 'Alif-1'), ('Bay-1', 'Bay-1'), ('Jeem-1', 'Jeem-1'), ('Daal-1', 'Daal-1'), ('Hay-1', 'Hay-1'), ('Wao-1', 'Wao-1')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='type_data',
            field=models.CharField(blank=True, default='Massavi', max_length=50, null=True),
        ),
    ]
