# Generated by Django 4.0 on 2022-01-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0019_alter_uploadimage_massavi_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='form_id',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
