# Generated by Django 4.0 on 2022-01-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0023_alter_uploadimage_form_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cities_list',
        ),
        migrations.DeleteModel(
            name='Geeks_Model',
        ),
    ]
