# Generated by Django 4.0 on 2022-01-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0024_delete_cities_list_delete_geeks_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='form_id',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
