# Generated by Django 4.0 on 2022-01-17 10:27

from django.db import migrations, models
import imageuploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0026_alter_uploadimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=imageuploader.models.content_file_name),
        ),
    ]
